### ISSUE TITLE
TypeError when asking y-xml.getDom() object

### ISSUE THREAD

**Issue by cphyc** [rwth-acis/y-xml#1]
Hi,
I get a `TypeError: this._model is undefined` when I try to cal Y-XML.getDom.
The code I'm using is:

     var connector = new Y.WebRTC("test", {url: config.server});

     var y = new Y(connector);
     var yxml = new Y.Xml(document.getElementById("comm"));

     connector.whenSynced(function() {
       y.val("xml", yxml);
     });
     yxml.getDom(); // ← error here

**Comment by DadaMonad** [comment]
You have to put yxml on the y object first, before you can use it. Otherwise the types model cannot be defined. You can work on your shared structure even when you are not synced yet: so do the following

     var connector = new Y.WebRTC("test", {url: config.server});

     var y = new Y(connector);
     var yxml = new Y.Xml(document.getElementById("comm"));

     // Set it here
     y.val("myxml",yxml)

     /* leave this
     connector.whenSynced(function() {
       y.val("xml", yxml);
     });
     */
     yxml.getDom(); // ← error here

I'm going to implement a meaningful errormessage for this.

**Comment by cphyc** [comment]
Wouldn't it leave me with two objects ("xml" and "myxml" in my y object) ? If so, what's the purpose of doing so?

**Comment by DadaMonad** [comment]
I commented out the following portion of code:
```
 /* leave this
 connector.whenSynced(function() {
   y.val("xml", yxml);  // you have to execute this _before_ you call yxml.getDom
 });
 */
```
So you would end up with only "myxml" in your y object. The reason why I commented it is that the callback function is executed sometime _after_ the `yxml.getDom()` is executed. The following will also work:
```
var connector = new Y.WebRTC("test", {url: config.server});

var y = new Y(connector);
var yxml = new Y.Xml(document.getElementById("comm"));

// Set it here
y.val("myxml",yxml)

connector.whenSynced(function() {
   y.val("xml", yxml);
   yxml.getDom(); // ← no error here
});

```

**Comment by DadaMonad** [comment]
I close this because I implemented a warning
