### ISSUE TITLE
TypeError: this._model.val(...) is undefined

### ISSUE THREAD

**Issue by cphyc** [rwth-acis/y-xml#2]
When I do a modification in one browser, the following error is thrown in the other one : `TypeError: this._model.val(...) is undefined` (in FF).

My code is 
```javascript
var connector = new Y.WebRTC("test", {url: config.server});

var y = new Y(connector);
var p = document.getElementById("test");
var yxml = new Y.Xml(p);

y.val("xml", yxml);
```

**Comment by DadaMonad** [comment]
Do you execute the same code in both browsers?

**Comment by cphyc** [comment]
It seems like I had a background process still running on another code. I closed it and it's now functional.

**Comment by cphyc** [comment]
Sorry for the false report.

**Comment by DadaMonad** [comment]
No problem
